---
abstract: 'Document Availability Information API'
author:
  - 'Jakob Voss'
build_requires:
  English: 0
  File::Spec: 0
  Test::More: 0
  Test::Perl::Critic: 0
  URI: 0
  XML::LibXML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DAIA
requires:
  CGI: 0
  Carp: 0
  Carp::Clan: 0
  Data::Dumper: 0
  Data::Validate::URI: 0
  DateTime: 0
  DateTime::Duration: 0
  DateTime::Format::Duration: 0
  Encode: 0
  Exporter: 0
  IO::File: 0
  IO::Scalar: 0
  JSON: 0
  LWP::Simple: 0
  POSIX: 0
  Scalar::Util: 0
  UNIVERSAL: 0
  XML::Simple: 0
  base: 0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/gbv/daia/issues
  repository: https://github.com/gbv/daia
version: 0.35
